### ISSUE TITLE
Commit checker should verify generated files are updated correctly

### ISSUE THREAD

**Issue by nielsmh** [OpenTTD/CompileFarm#14]
There are several generated files checked in to the main repository out of convenience:
- Makefiles
- Visual Studio project files
- Scripting system headers (`src/script/(ai,game,template)/`)

These files should always be kept updated when a commit modifies the source files they are generated from. The commit checker should verify that re-generating these files do not produce a diff, and fail if there is a difference.

Other generated files checked in are baseset definition files, which are built from a template and translations. Since these are closely tied to translations they should likely be handled by Eints, out of scope of this ticket.

Lastly there is `openttd.grf`, which requires additional tooling to generate, and might have binary differences depending on the exact versions of the tools used. It should possibly be maintained by a separate job, out of scope of this ticket.

**Comment by LordAro** [comment]
No longer an issue thanks to OpenTTD/OpenTTD#7270 & OpenTTD/OpenTTD#8192
