### ISSUE TITLE
Commit checker always expect origin/master, even for non master PRs

### ISSUE THREAD

**Issue by glx22** [OpenTTD/CompileFarm#29]
For backports we open PRs against origin/release/XXX but commit checker assumes origin/master, and fails.

**Comment by TrueBrain** [comment]
Two possible solutions I can think of:
1) Assume we use Azure Pipelines, and check for the "System.PullRequest.TargetBranch" variable to know the tracking branch.
2) allow an optional additional parameter with the tracking branch, and set that via the CI.

Most likely the second is nicer.

**Comment by glx22** [comment]
In Azure Pipelines docker task parameters for run command there is

`envVars`Environment variables | (Optional) Environment variables for the Docker container. Specify each name-value pair on a new line.
-- | --

So second solution should not be too difficult. And maybe SYSTEM_PULLREQUEST_TARGETBRANCH is already passed without needing to use envVars parameter.

**Comment by TrueBrain** [comment]
No clue what I was smocking earlier today, but I think it would be good if these Dockers don't know about Azure. But yeah, mapping the variable in via env is fine. Extra parameter, env variable .. tomato tomato :)
